### ISSUE TITLE
IMAGE Error Could not find image file

### ISSUE THREAD

**Issue by baselbers** [mpdf/mpdf#275]
Image is accessible, but mPDF can't find it. Please help. I'm lost!
http://www.thenextwomen.com/wp-content/uploads/2016/11/TheNextWomen.jpg

I'm using [this ](https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/includes/abstracts/abstract-bewpi-invoice.php#L436)code.

Tried every possible solution:
- Changed permissions
- Converted from png to jpg
- Relative path
- Base64
- No spaces in url
- Enabled debugging
- [No HTTPS](https://www.drupal.org/node/2478597)

PHP 5.6
allow_url_fopen On (but should also work if it's Off right?)
Linux server

Fatal error: Uncaught exception 'MpdfException' with message 'IMAGE Error (http://www.thenextwomen.com/wp-content/uploads/2016/11/TheNextWomen.jpg): Could not find image file' in /home/cluster-sites/8098/t/thenextwomen.com/public_html/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/mpdf.php:11752
Stack trace:
#0 /home/cluster-sites/8098/t/thenextwomen.com/public_html/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/mpdf.php(11831): mPDF->_imageError('http://www.then...', true, 'Could not find ...')
#1 /home/cluster-sites/8098/t/thenextwomen.com/public_html/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/Tag.php(3271): mPDF->_getImage('http://www.then...', true, true, 'http://www.then...', false)
#2 /home/cluster-sites/8098/t/thenextwomen.com/public_html/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/mpdf.php(16543): Tag->OpenTag('IMG', Array, Array, 7)
#3 /home/cluster-sites/8098/t/thenextwomen.com/public_html/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/mpdf.php(15105): mPDF->WriteHTML('<table in /home/cluster-sites/8098/t/thenextwomen.com/public_html/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/mpdf.php on line 11752

**Comment by jakejackson1** [comment]
@finwe I have had similar reports of image problems like this in the past (haven't been able to track down the exact problem because I cannot replicate it on any servers I can test with). However, I implemented a patch on my version of Mpdf 12 months ago which resolved an issue with Mpdf prepending an absolute image path with the site URL. It might be worth adding as a work around:

Line 13982 of mpdf.php: `elseif ((strpos($path, ":/") === false || strpos($path, ":/") > 10) && !is_file($path)) {`

Lines 11614-11636 of mpdf.php could also use a refractor at some stage to better manage the fallback options for getting the image. But then again, all of Mpdf could use a refractor ;)

**Comment by baselbers** [comment]
Fixed it. 8d6ed8105c848144dcd4f657cd37b44b8d50cc25

**Comment by iNviNho** [comment]
Guys i am having same exact problem, what was causing this problem? my image is set in CSS file :-\

**Comment by sazr** [comment]
I am getting the same error. The error occurs with the following html: `<img src="/images/preview-logo.png">`. 

Some have said the issue is that the domain request made internally on the server is not routed properly to `127.0.0.1`. I have set my `/etc/hosts` file so that my domain is under `127.0.0.1` and restarted my apache server but the issue still exhibits itself. I think this issue needs to be reopened and mentioned in the mpdf manual's 'Known Issues'.

**Comment by Nukro** [comment]
I also have this error with **absolute paths** to the images. It's totaly weird, since it looks like the error/problem comes for about 4-5 mins and then the error disappears again. What could cause this problem?

I am using mpdf-6.1.2.

**Comment by iNviNho** [comment]
@Nukro  i somehow solved it in very weird way, i changed host of image file, in another words, i uploaded my images to different hosting

**Comment by damelco** [comment]
> Image is accessible, but mPDF can't find it. Please help. I'm lost!
http://www.thenextwomen.com/wp-content/uploads/2016/11/TheNextWomen.jpg

perhaps that link is accessible to **your** browser ... I suspect it is not accessible to **your** server. particular if the image AND mPDF are on the same machine.

try using **get_stylesheet_directory()** instead of **get_stylesheet_directory_uri()** to generate the path string.

peace

-DJ

**Comment by Alex-arib** [comment]
> I am getting the same error. The error occurs with the following html: `<img src="/images/preview-logo.png">`.
> 
> Some have said the issue is that the domain request made internally on the server is not routed properly to `127.0.0.1`. I have set my `/etc/hosts` file so that my domain is under `127.0.0.1` and restarted my apache server but the issue still exhibits itself. I think this issue needs to be reopened and mentioned in the mpdf manual's 'Known Issues'.

I removed the line with the domain and the ip. Everything worked! Only  line "127.0.0.1 localhost" left
